[package]
name = "ethers-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["signer-local", "signers", "rpc", "rpc-client", "providers","transports","transport-http", "reqwest"] }
tokio = "1.43.0"
tower-layer = "0.3.3"
